model_name_or_path: TinyLlama/TinyLlama-1.1B-Chat-v1.0
model_name: tinyllama
model_config:
  _target_: trl.ModelConfig
  model_revision: main
  torch_dtype: float32
  attn_implementation: flash_attention_2